// REQUIREMENTS
var express = require('express');
var router = express.Router();

var User = require('../models/users.js');

var newUser = [{"gender":"Male","firstName":"Joshua","lastName":"Berry","email":"jberry0@nydailynews.com","password":"password","age":21,"about":"in consequat ut nulla sed accumsan felis ut at dolor quis"},
{"gender":"Female","firstName":"Sandra","lastName":"Hughes","email":"shughes1@drupal.org","password":"password","age":22,"about":"quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam"},
{"gender":"Female","firstName":"Christine","lastName":"Bishop","email":"cbishop2@state.gov","password":"password","age":23,"about":"velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo"},
{"gender":"Male","firstName":"Ryan","lastName":"Lopez","email":"rlopez3@narod.ru","password":"password","age":24,"about":"arcu libero rutrum ac lobortis vel dapibus at diam nam tristique"},
{"gender":"Male","firstName":"Eugene","lastName":"Hart","email":"ehart4@weibo.com","password":"password","age":25,"about":"duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui"},
{"gender":"Male","firstName":"Larry","lastName":"Day","email":"lday5@pinterest.com","password":"password","age":26,"about":"in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit"},
{"gender":"Male","firstName":"Willie","lastName":"Hicks","email":"whicks6@xinhuanet.com","password":"password","age":27,"about":"pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna"},
{"gender":"Male","firstName":"Charles","lastName":"Williamson","email":"cwilliamson7@answers.com","password":"password","age":28,"about":"elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy"},
{"gender":"Female","firstName":"Dorothy","lastName":"Richardson","email":"drichardson8@plala.or.jp","password":"password","age":29,"about":"turpis a pede posuere nonummy integer non velit donec diam neque"},
{"gender":"Male","firstName":"Wayne","lastName":"Rodriguez","email":"wrodriguez9@nature.com","password":"password","age":30,"about":"tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi"},
{"gender":"Female","firstName":"Judy","lastName":"Patterson","email":"jpattersona@goo.ne.jp","password":"password","age":31,"about":"nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo"},
{"gender":"Male","firstName":"Raymond","lastName":"Brown","email":"rbrownb@e-recht24.de","password":"password","age":32,"about":"nulla nunc purus phasellus in felis donec semper sapien a"},
{"gender":"Female","firstName":"Stephanie","lastName":"Fox","email":"sfoxc@themeforest.net","password":"password","age":33,"about":"justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris"},
{"gender":"Female","firstName":"Sara","lastName":"Webb","email":"swebbd@craigslist.org","password":"password","age":34,"about":"id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque"},
{"gender":"Male","firstName":"James","lastName":"Carter","email":"jcartere@jigsy.com","password":"password","age":35,"about":"morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id"},
{"gender":"Female","firstName":"Michelle","lastName":"Rose","email":"mrosef@qq.com","password":"password","age":36,"about":"ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede"},
{"gender":"Female","firstName":"Patricia","lastName":"Carter","email":"pcarterg@google.com","password":"password","age":37,"about":"nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec"},
{"gender":"Male","firstName":"Steven","lastName":"Hernandez","email":"shernandezh@earthlink.net","password":"password","age":38,"about":"luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur"},
{"gender":"Male","firstName":"Brian","lastName":"Harvey","email":"bharveyi@google.ru","password":"password","age":39,"about":"condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris"},
{"gender":"Female","firstName":"Frances","lastName":"Henry","email":"fhenryj@wordpress.com","password":"password","age":40,"about":"odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique"},
{"gender":"Female","firstName":"Kelly","lastName":"Cole","email":"kcolek@businessinsider.com","password":"password","age":41,"about":"turpis a pede posuere nonummy integer non velit donec diam neque"},
{"gender":"Female","firstName":"Karen","lastName":"Romero","email":"kromerol@umich.edu","password":"password","age":42,"about":"ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula"},
{"gender":"Male","firstName":"Larry","lastName":"Young","email":"lyoungm@apache.org","password":"password","age":43,"about":"at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis"},
{"gender":"Male","firstName":"Martin","lastName":"Hunter","email":"mhuntern@microsoft.com","password":"password","age":44,"about":"at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula"},
{"gender":"Male","firstName":"Todd","lastName":"Ray","email":"trayo@jimdo.com","password":"password","age":45,"about":"tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi"},
{"gender":"Male","firstName":"Eric","lastName":"Richards","email":"erichardsp@fema.gov","password":"password","age":46,"about":"congue etiam justo etiam pretium iaculis justo in hac habitasse platea"},
{"gender":"Female","firstName":"Tina","lastName":"Knight","email":"tknightq@g.co","password":"password","age":47,"about":"a pede posuere nonummy integer non velit donec diam neque vestibulum"},
{"gender":"Female","firstName":"Jessica","lastName":"Fuller","email":"jfullerr@cyberchimps.com","password":"password","age":48,"about":"est donec odio justo sollicitudin ut suscipit a feugiat et"},
{"gender":"Female","firstName":"Rachel","lastName":"Wallace","email":"rwallaces@posterous.com","password":"password","age":49,"about":"interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet"},
{"gender":"Female","firstName":"Joan","lastName":"Mason","email":"jmasont@narod.ru","password":"password","age":50,"about":"nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec"},
{"gender":"Male","firstName":"Billy","lastName":"Wells","email":"bwellsu@blog.com","password":"password","age":21,"about":"lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate"},
{"gender":"Male","firstName":"Wayne","lastName":"Howard","email":"whowardv@earthlink.net","password":"password","age":22,"about":"ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla"},
{"gender":"Female","firstName":"Jean","lastName":"Hughes","email":"jhughesw@ow.ly","password":"password","age":23,"about":"at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor"},
{"gender":"Male","firstName":"Aaron","lastName":"Campbell","email":"acampbellx@php.net","password":"password","age":24,"about":"sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean"},
{"gender":"Male","firstName":"Wayne","lastName":"Spencer","email":"wspencery@shinystat.com","password":"password","age":25,"about":"arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium"},
{"gender":"Female","firstName":"Heather","lastName":"Thompson","email":"hthompsonz@homestead.com","password":"password","age":26,"about":"a odio in hac habitasse platea dictumst maecenas ut massa quis"},
{"gender":"Male","firstName":"Raymond","lastName":"Bell","email":"rbell10@newsvine.com","password":"password","age":27,"about":"dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at"},
{"gender":"Male","firstName":"Earl","lastName":"Harris","email":"eharris11@is.gd","password":"password","age":28,"about":"ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia"},
{"gender":"Female","firstName":"Deborah","lastName":"Diaz","email":"ddiaz12@si.edu","password":"password","age":29,"about":"in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse"},
{"gender":"Male","firstName":"Philip","lastName":"Lawrence","email":"plawrence13@furl.net","password":"password","age":30,"about":"etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla"},
{"gender":"Male","firstName":"Louis","lastName":"Rivera","email":"lrivera14@usatoday.com","password":"password","age":31,"about":"in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla"},
{"gender":"Male","firstName":"Charles","lastName":"Phillips","email":"cphillips15@msu.edu","password":"password","age":32,"about":"vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna"},
{"gender":"Male","firstName":"Robert","lastName":"Russell","email":"rrussell16@forbes.com","password":"password","age":33,"about":"amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu"},
{"gender":"Male","firstName":"Phillip","lastName":"West","email":"pwest17@cdc.gov","password":"password","age":34,"about":"quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede"},
{"gender":"Male","firstName":"Alan","lastName":"Mccoy","email":"amccoy18@woothemes.com","password":"password","age":35,"about":"maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante"},
{"gender":"Male","firstName":"Mark","lastName":"Burke","email":"mburke19@weebly.com","password":"password","age":36,"about":"vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla"},
{"gender":"Male","firstName":"Carl","lastName":"Weaver","email":"cweaver1a@networksolutions.com","password":"password","age":37,"about":"sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at"},
{"gender":"Female","firstName":"Michelle","lastName":"Watson","email":"mwatson1b@lycos.com","password":"password","age":38,"about":"metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae"},
{"gender":"Male","firstName":"Brian","lastName":"Stanley","email":"bstanley1c@apache.org","password":"password","age":39,"about":"fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet"},
{"gender":"Female","firstName":"Dorothy","lastName":"Bryant","email":"dbryant1d@xinhuanet.com","password":"password","age":40,"about":"dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede"},
{"gender":"Female","firstName":"Ruth","lastName":"Taylor","email":"rtaylor1e@smh.com.au","password":"password","age":41,"about":"ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis"},
{"gender":"Female","firstName":"Julie","lastName":"Gomez","email":"jgomez1f@ehow.com","password":"password","age":42,"about":"eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus"},
{"gender":"Female","firstName":"Anne","lastName":"Ross","email":"aross1g@forbes.com","password":"password","age":43,"about":"volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus"},
{"gender":"Female","firstName":"Tina","lastName":"Little","email":"tlittle1h@opensource.org","password":"password","age":44,"about":"turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam"},
{"gender":"Male","firstName":"Randy","lastName":"Meyer","email":"rmeyer1i@networksolutions.com","password":"password","age":45,"about":"sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam"},
{"gender":"Male","firstName":"Raymond","lastName":"Pierce","email":"rpierce1j@diigo.com","password":"password","age":46,"about":"adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus"},
{"gender":"Female","firstName":"Rebecca","lastName":"Sanders","email":"rsanders1k@imdb.com","password":"password","age":47,"about":"sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan"},
{"gender":"Male","firstName":"Charles","lastName":"Fowler","email":"cfowler1l@bluehost.com","password":"password","age":48,"about":"amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu"},
{"gender":"Female","firstName":"Tammy","lastName":"Kelly","email":"tkelly1m@indiatimes.com","password":"password","age":49,"about":"quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus"},
{"gender":"Male","firstName":"Martin","lastName":"Johnston","email":"mjohnston1n@list-manage.com","password":"password","age":50,"about":"luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus"},
{"gender":"Male","firstName":"Randy","lastName":"Moreno","email":"rmoreno1o@microsoft.com","password":"password","age":21,"about":"curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis"},
{"gender":"Female","firstName":"Margaret","lastName":"Cook","email":"mcook1p@omniture.com","password":"password","age":22,"about":"velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis"},
{"gender":"Male","firstName":"Nicholas","lastName":"Stanley","email":"nstanley1q@seattletimes.com","password":"password","age":23,"about":"neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus"},
{"gender":"Female","firstName":"Anne","lastName":"Mcdonald","email":"amcdonald1r@lulu.com","password":"password","age":24,"about":"congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in"},
{"gender":"Male","firstName":"Henry","lastName":"Gray","email":"hgray1s@biglobe.ne.jp","password":"password","age":25,"about":"aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus"},
{"gender":"Male","firstName":"Brandon","lastName":"Palmer","email":"bpalmer1t@comcast.net","password":"password","age":26,"about":"sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue"},
{"gender":"Female","firstName":"Jean","lastName":"Berry","email":"jberry1u@disqus.com","password":"password","age":27,"about":"metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh"},
{"gender":"Male","firstName":"Matthew","lastName":"Garcia","email":"mgarcia1v@cdc.gov","password":"password","age":28,"about":"in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod"},
{"gender":"Female","firstName":"Stephanie","lastName":"Greene","email":"sgreene1w@si.edu","password":"password","age":29,"about":"quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea"},
{"gender":"Male","firstName":"Louis","lastName":"Olson","email":"lolson1x@jigsy.com","password":"password","age":30,"about":"pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede"},
{"gender":"Female","firstName":"Katherine","lastName":"Peters","email":"kpeters1y@bravesites.com","password":"password","age":31,"about":"ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor"},
{"gender":"Male","firstName":"Samuel","lastName":"Franklin","email":"sfranklin1z@twitter.com","password":"password","age":32,"about":"ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus"},
{"gender":"Female","firstName":"Joyce","lastName":"Mitchell","email":"jmitchell20@e-recht24.de","password":"password","age":33,"about":"ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in"},
{"gender":"Female","firstName":"Lori","lastName":"Duncan","email":"lduncan21@1688.com","password":"password","age":34,"about":"justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna"},
{"gender":"Male","firstName":"Bruce","lastName":"Tucker","email":"btucker22@godaddy.com","password":"password","age":35,"about":"imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum"},
{"gender":"Female","firstName":"Denise","lastName":"Burton","email":"dburton23@webs.com","password":"password","age":36,"about":"eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu"},
{"gender":"Male","firstName":"Henry","lastName":"Lane","email":"hlane24@stanford.edu","password":"password","age":37,"about":"posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet"},
{"gender":"Female","firstName":"Andrea","lastName":"Romero","email":"aromero25@livejournal.com","password":"password","age":38,"about":"mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer"},
{"gender":"Male","firstName":"Antonio","lastName":"Harvey","email":"aharvey26@phoca.cz","password":"password","age":39,"about":"sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea"},
{"gender":"Male","firstName":"Roger","lastName":"Garza","email":"rgarza27@apple.com","password":"password","age":40,"about":"risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam"},
{"gender":"Male","firstName":"Frank","lastName":"Payne","email":"fpayne28@army.mil","password":"password","age":41,"about":"convallis nunc proin at turpis a pede posuere nonummy integer non velit donec"},
{"gender":"Female","firstName":"Margaret","lastName":"Myers","email":"mmyers29@phpbb.com","password":"password","age":42,"about":"in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu"},
{"gender":"Female","firstName":"Joan","lastName":"Harper","email":"jharper2a@ucsd.edu","password":"password","age":43,"about":"posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed"},
{"gender":"Female","firstName":"Stephanie","lastName":"Burke","email":"sburke2b@google.ru","password":"password","age":44,"about":"quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac"},
{"gender":"Female","firstName":"Kelly","lastName":"Martin","email":"kmartin2c@xinhuanet.com","password":"password","age":45,"about":"ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan"},
{"gender":"Female","firstName":"Lillian","lastName":"Henderson","email":"lhenderson2d@google.de","password":"password","age":46,"about":"magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt"},
{"gender":"Female","firstName":"Virginia","lastName":"Gilbert","email":"vgilbert2e@chron.com","password":"password","age":47,"about":"dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at"},
{"gender":"Male","firstName":"Earl","lastName":"Riley","email":"eriley2f@bluehost.com","password":"password","age":48,"about":"lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus"},
{"gender":"Female","firstName":"Annie","lastName":"Parker","email":"aparker2g@a8.net","password":"password","age":49,"about":"in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem"},
{"gender":"Female","firstName":"Judy","lastName":"Marshall","email":"jmarshall2h@house.gov","password":"password","age":50,"about":"donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit"},
{"gender":"Female","firstName":"Laura","lastName":"Richards","email":"lrichards2i@youtu.be","password":"password","age":21,"about":"maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante"},
{"gender":"Male","firstName":"Nicholas","lastName":"West","email":"nwest2j@census.gov","password":"password","age":22,"about":"erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque"},
{"gender":"Female","firstName":"Martha","lastName":"Bradley","email":"mbradley2k@miitbeian.gov.cn","password":"password","age":23,"about":"porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla"},
{"gender":"Male","firstName":"Nicholas","lastName":"Brown","email":"nbrown2l@cbslocal.com","password":"password","age":24,"about":"velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis"},
{"gender":"Male","firstName":"Keith","lastName":"Brown","email":"kbrown2m@smugmug.com","password":"password","age":25,"about":"consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac"},
{"gender":"Female","firstName":"Rachel","lastName":"Freeman","email":"rfreeman2n@biblegateway.com","password":"password","age":26,"about":"aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit"},
{"gender":"Male","firstName":"Wayne","lastName":"Kelley","email":"wkelley2o@xinhuanet.com","password":"password","age":27,"about":"maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem"},
{"gender":"Female","firstName":"Sandra","lastName":"Davis","email":"sdavis2p@cmu.edu","password":"password","age":28,"about":"tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh"},
{"gender":"Male","firstName":"Phillip","lastName":"Hayes","email":"phayes2q@sphinn.com","password":"password","age":29,"about":"ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien"},
{"gender":"Female","firstName":"Tammy","lastName":"Diaz","email":"tdiaz2r@jimdo.com","password":"password","age":30,"about":"sapien varius ut blandit non interdum in ante vestibulum ante ipsum"}];

// SEEDING
router.get('/', function(req, res){
  User.create(newUser, function(err){
    if (err){
      console.log(err);
      res.send('Error seeding database');
    } else {
      console.log('Seed completed');
      res.redirect('/');
    }
  });
});

// EXPORTING
module.exports = router;
